kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    service: discovery-server
  name: discovery-server
  namespace: bytebusters
spec:
  selector:
    matchLabels:
      service: discovery-server
  template:
    metadata:
      labels:
        service: discovery-server
    spec:
      containers:
      - name: discovery-server-container
        image: ghcr.io/ivan-bobrov/make-spring-petclinic-microservices-crash/spring-petclinic-discovery-server
        imagePullPolicy: Always
        ports:
          - name: disc-server
            containerPort: 8761
      imagePullSecrets:
      - name: dockerconfigjson-github-com

---

kind: Service
apiVersion: v1
metadata:
  labels:
    service: discovery-server
  name: discovery-server
  namespace: bytebusters
spec:
  ports:
    - name: discovery-server
      port: 8761
      targetPort: 8761
  selector:
    service: discovery-server
  type: ClusterIP
